# Generated by Django 3.2 on 2021-04-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.CharField(max_length=10, verbose_name='Data de emissão')),
                ('invoice_number', models.CharField(max_length=7, verbose_name='Número da nota')),
                ('invoice_key', models.CharField(max_length=44, verbose_name='Chave da nota')),
                ('part_number', models.CharField(max_length=12, verbose_name='Número do desenho')),
                ('value_total_drawing', models.CharField(max_length=10, verbose_name='Valor total do desenho')),
                ('value_unit_drawing', models.CharField(max_length=10, verbose_name='Valor unitário do desenho')),
                ('amount_drawing', models.CharField(max_length=10, verbose_name='Quantidade solicitada')),
                ('number_progressive', models.CharField(max_length=5, verbose_name='Número do progressivo')),
                ('date_create_progressive', models.CharField(max_length=10, verbose_name='Data de criação')),
            ],
        ),
    ]
